Implement a GET call to load all food resources on home page
LosAngelesDataProject/LADP pull request #40
Opened 2024-09-25 21:05 UTC by victoremartinez18

Created a service file called foodResourcesService.js to implement the GET call for loading all the food resources from the database. Added the getFoodResources method to the Home component to make the call, pass the array to the component, and handle any errors. Updated the propTypes to reflect the data type coming from the database and refactored the code in the SearchResults component by adding a useEffect to account for the delay from the API response, ensuring proper functionality when clicking cards on the left side of the map.

2024-09-25 21:40 UTC, jjcanell77 commented on react/src/services/foodResourcesService.js
> +  return axios(config);
Is it returning the correct data and returning the correct error if applicable?
  return axios(config)
    .then((response) => response.data)
    .catch((error) => {
      return Promise.reject(error);
    });
};

2024-09-26 13:11 UTC, victoremartinez18 commented on react/src/services/foodResourcesService.js
> +  return axios(config);
Yes it is, I am calling the method inside the Home component, and created a state for the result variable, also put it inside the useEffect to handle the delayed response from the API.
`foodResourcesService
      .getFoodResources()
      .then(onGetFoodResourcesSuccess)
      .catch(onGetFoodResourcesError);

const onGetFoodResourcesSuccess = (response) => {
     setResults(() => [...response.data]);
  };

  const onGetFoodResourcesError = (error) => {
    console.error(error);
  };`

I can add a toastr for the error handler, also I was thinking that we might want to have some sort of backup data stored locally in case there is an error, but that can be discussed in the next meeting.

2024-10-02 18:26 UTC, na106 approved these changes

2024-10-09 17:21 UTC, jjcanell77 approved these changes

2024-10-09 17:21 UTC, jjcanell77 commented on react/src/services/foodResourcesService.js
> +  return axios(config);
`.then((response) => response.data)` This would just simplify the response before hitting `onGetFoodResourcesSuccess` so that way it returns only the data part of the response.

By error I was inferring a spot to add a general error handling not specifically just the error response in your home component. It would be like like if you wanted the `console.error(error)`  to occur only  for everyone that calls `getFoodResources()` and has an error you can add it to the service and not have to redefine it every time in the component.

2024-10-10 05:44 UTC, jmedina1329 requested changes

2024-10-10 05:44 UTC, jmedina1329 commented on dotnet/.vs/VSWorkspaceState.json
Posting as a reminder and to block merging....

Need to remove all the extra files here from the PR

2024-10-10 19:40 UTC, victoremartinez18 commented on dotnet/.vs/VSWorkspaceState.json
Reverted to previous commit, unstaged the changes and only added the files I modified or created. Now the files changed count is only 4 as expected.

2024-10-10 21:02 UTC, jmedina1329 approved these changes

2024-10-10 21:02 UTC, merged