enabled isolated scrolling for organization list on home page
LosAngelesDataProject/LADP pull request #41
Opened 2024-09-26 06:24 UTC by AWBeckstrom

Encapsulated very long data array of organizations inside a scrollable container having identical sizing to the location map in the column to its right. Pictures included for review.
![resultlistscroll](https://github.com/user-attachments/assets/92a64b72-5cdb-4391-908e-067727d2e175)
![bottomresultlistalignment](https://github.com/user-attachments/assets/3ada35eb-b88f-4b5c-b6aa-a5d3904d96f0)

2024-09-26 13:21 UTC, victoremartinez18 approved these changes
Looks good.

2024-09-26 19:56 UTC, AWBeckstrom commented
Since this has been posted. A trello card requesting the title to be removed over the map.
I have completed that request on PR#42. Therefore I anticipate that I will need to remove the title above the organization list as well.

2024-10-02 18:27 UTC, na106 approved these changes

2024-10-09 17:18 UTC, jjcanell77 requested changes
The implementation looks good but, this doesn't seem to answer the "Load as you scroll" feature this was meant to address. It was supposed to look like Facebook for example if you scroll down to fast you may notice some things are still loading meaning they were not loaded on start. I think the idea was only to load 15 images at time to make the query to the database smaller and therefore make the load quicker  for the information the user was looking at. I think this should be discussed at the meeting today before this is merged.

2024-10-10 05:26 UTC, closed without merging